// Mocks generated by Mockito 5.0.16 from annotations
// in cart_tul/test/domain/usecases/get_product_list_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:cart_tul/core/error/failure.dart' as _i5;
import 'package:cart_tul/domain/entities/cart.dart' as _i7;
import 'package:cart_tul/domain/entities/product.dart' as _i6;
import 'package:cart_tul/domain/repositories/cart_repository.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i3.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>> getProductList() =>
      (super.noSuchMethod(Invocation.method(#getProductList, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Product>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> checkoutCart(_i7.Cart? cart) =>
      (super.noSuchMethod(Invocation.method(#checkoutCart, [cart]),
              returnValue: Future<_i2.Either<_i5.Failure, bool>>.value(
                  _FakeEither_0<_i5.Failure, bool>()))
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);
  @override
  String toString() => super.toString();
}
